#ifndef _ENUMS_H
#define _ENUMS_H

enum REQUEST_TYPE{
	REQUEST_TYPE_UPDATE_CUSTOMER,
	REQUEST_TYPE_SHOW_MENU,
	REQUEST_TYPE_PLACE_ORDER,
	REQUEST_TYPE_CHECK_OUT,
};

enum RESPONSE_TYPE{
	RESPONSE_TYPE_UPDATE_CUSTOMER,
	RESPONSE_TYPE_SHOW_MENU,
	RESPONSE_TYPE_PLACE_ORDER,
	RESPONSE_TYPE_CHECK_OUT,
	RESPONSE_TYPE_DISH_READY
};

enum RESPONSE_RESULT_CODE{
	RESPONSE_RESULT_CODE_OK,
	RESPONSE_RESULT_CODE_FAILURE
};



#endif